POST http://localhost:2000/canticles
content-type: application/json

{
  "lyric": "Test lyric",
  "stage": "Test Stage",
  "page": 999,
  "title": "Test title",
  "subtitle": "Test subtitle",
  "tone": "Test tone",
  "capo": 999,
  "tags": ["psalm"]
}