PUT http://localhost:2000/canticles/999
content-type: application/json


{
  "lyric": "Test lyric",
  "stage": "liturgy",
  "page": 999,
  "title": "Test title",
  "subtitle": "Test subtitle",
  "tone": "Test tone",
  "capo": 999,
  "tags": ["psalm"]
}